// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = CallToActionSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
	/**
	 * Slice Zone field in *blog*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
	 * Meta Title field in *blog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: blog.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *blog*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: blog.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *blog*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog.meta_image
	 * - **Tab**: SEO & Metadata
	slicemachine * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<BlogDocumentData>,
	'blog',
	Lang
>;

interface CategoryDocumentData {}

/**
 * category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<CategoryDocumentData>,
	'category',
	Lang
>;

export type AllDocumentTypes = BlogDocument | CategoryDocument;

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
	/**
	 * Image field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * title field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * paragraph field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.default.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * buttonLink field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Redirect URL for CTA button
	 * - **API ID Path**: call_to_action.default.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonLink: prismic.LinkField;

	/**
	 * buttonLabel field in *CallToAction → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Label for CTA button
	 * - **API ID Path**: call_to_action.default.primary.buttonLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttonLabel: prismic.KeyTextField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CallToActionSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *CallToAction → AlignLeft → Primary*
 */
export interface CallToActionSliceAlignLeftPrimary {
	/**
	 * Image field in *CallToAction → AlignLeft → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.alignLeft.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * title field in *CallToAction → AlignLeft → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.alignLeft.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * paragraph field in *CallToAction → AlignLeft → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: call_to_action.alignLeft.primary.paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;

	/**
	 * buttonLink field in *CallToAction → AlignLeft → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Redirect URL for CTA button
	 * - **API ID Path**: call_to_action.alignLeft.primary.buttonLink
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	buttonLink: prismic.LinkField;

	/**
	 * buttonLabel field in *CallToAction → AlignLeft → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Label for CTA button
	 * - **API ID Path**: call_to_action.alignLeft.primary.buttonLabel
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	buttonLabel: prismic.KeyTextField;
}

/**
 * AlignLeft variation for CallToAction Slice
 *
 * - **API ID**: `alignLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceAlignLeft = prismic.SharedSliceVariation<
	'alignLeft',
	Simplify<CallToActionSliceAlignLeftPrimary>,
	never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault | CallToActionSliceAlignLeft;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<'call_to_action', CallToActionSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			BlogDocument,
			BlogDocumentData,
			BlogDocumentDataSlicesSlice,
			CategoryDocument,
			CategoryDocumentData,
			AllDocumentTypes,
			CallToActionSlice,
			CallToActionSliceDefaultPrimary,
			CallToActionSliceAlignLeftPrimary,
			CallToActionSliceVariation,
			CallToActionSliceDefault,
			CallToActionSliceAlignLeft
		};
	}
}
